### ISSUE TITLE
Add stripe logo / image for payment module

### ISSUE THREAD

**Issue by RobinTheHood** [RobinTheHood/modified-stripe#11]
Check if there is a logo for Stripe that is free to use. If so, include this logo like the other logos.

![modified_payment_logos](https://user-images.githubusercontent.com/6323551/221970992-643c9806-932d-4bf9-9bfb-1c62dddcff18.png)

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.

**Comment by grandeljay** [comment]
Hello @tarunsamanta2k20,

welcome and thank you for volunteering for this issue!

Please also provide a link or information on the image being free to use and if attribution is required, etc. I'll assign you and if you have any further questions please do not hesitate to ask here or on our [Discord server](https://discord.gg/kfUamcNBRH).

Looking forward to collaborating!
\- Jay

**Comment by tarunsamanta2k20** [comment]
@grandeljay where i have to add this logo as i couldn't see other images?

**Comment by grandeljay** [comment]
Hey @tarunsamanta2k20,

that's a very good question! This project is still in its early development stages so we haven't really thought about it until now.

Please place the logo (preferably an SVG) under:
```
/src/vendor-no-composer/robinthehood/Stripe/assets/img/stripe-logo.svg
```
