### ISSUE TITLE
Issue with Language Field Input in Module Settings

### ISSUE THREAD

**Issue by RobinTheHood** [RobinTheHood/modified-stripe#36]
The language field input in the module settings is not working reliably. When clicking on German or English, there is no indicator to show which tab is selected. Additionally, when dealing with multiple multilingual input fields, the fields themselves shift when switching the language of another field.

You can find the settings here:
/admin/modules.php?set=payment&module=payment_rth_stripe&action=edit

**Proposed Solution:**

One potential solution would be to address this issue not solely through CSS or by using JavaScript alone.

**Comment by grandeljay** [comment]
I think I initially built that. If you like I can further work on this.
